import type { Metadata } from "next";
import { Iceland, Roboto } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/utils/SessionWrapper";

const iceland = Iceland({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-iceland",
  display: "swap",
});
const roboto = Roboto({
  weight: ["300", "400"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${iceland.variable} ${roboto.variable}`}>
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
